apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongod
  name: mongod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongod
    spec:
      containers:
        - args:
            - mongod
          image: mongo:3.4.7
          name: mongod
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
